project_id = "iwcqutzgtpbdowghalnl"

[functions.initiate-payment]
verify_jwt = false

[functions.payment-ipn]
verify_jwt = false

[functions.process-ml-order]
verify_jwt = false

[functions.chatbot-api]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.database-cleanup]
verify_jwt = false
